/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj-1.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 2.76, -2.1]} scale={0.15}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Torii- Rojo']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Torii- Negro']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Torii-Gris']} />
      </group>
    </group>
  )
}

useGLTF.preload('/obj-1.glb')
