/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/obj-2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[3.19, 3.3, 0.77]} rotation={[-2.57, -1.56, -2.57]} scale={[0.52, 0.32, 0.64]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Casa1} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Tejado} />
      </group>
      <group position={[3.19, 2.58, 0.77]} rotation={[0, -Math.PI / 2, 0]} scale={0.41}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Casa1} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.maderaCasa} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials.maderaCasa} position={[3.19, 2.47, 0.67]} rotation={[-2.57, -1.56, -2.57]} scale={0.41} />
    </group>
  )
}

useGLTF.preload('/obj-2.glb')
