/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Tablero.geometry} material={materials.Puente} position={[0,0,0]} />
      <mesh geometry={nodes.Agua.geometry} material={materials.Agua} position={[0,0,0]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={4.93} />
      <group position={[0,0,0]}>
        <mesh geometry={nodes.Icosphere003_1.geometry} material={materials['Terreno-Base']} />
        <mesh geometry={nodes.Icosphere003_2.geometry} material={materials['Terreno- Nieve']} />
        <mesh geometry={nodes.Icosphere003_3.geometry} material={materials['Terreno - Verde']} />
        <mesh geometry={nodes.Icosphere003_4.geometry} material={materials['Terreno- Camino']} />
        <mesh geometry={nodes.Icosphere003_5.geometry} material={materials['Terreno- Roca']} />
      </group>
      <mesh geometry={nodes.Adorno.geometry} material={materials['Adorno- Roca']} position={[0,0,0]} />
      <mesh geometry={nodes.Adorno001.geometry} material={materials['Adorno- Roca']} position={[0,0,0]} />
      <group position={[0,0,0]} rotation={[0, 0.46, 0]}>
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials.Roca} />
        <mesh geometry={nodes.Icosphere_2.geometry} material={materials.Roca2} />
      </group>
      <group position={[0,0,0]} rotation={[-Math.PI, 1.52, -Math.PI]} scale={0.43}>
        <mesh geometry={nodes.Icosphere006.geometry} material={materials.Roca} />
        <mesh geometry={nodes.Icosphere006_1.geometry} material={materials.Roca2} />
      </group>
      <group position={[0,0,0]} rotation={[3.03, 0.95, -2.56]} scale={0.43}>
        <mesh geometry={nodes.Icosphere007.geometry} material={materials.Roca} />
        <mesh geometry={nodes.Icosphere007_1.geometry} material={materials.Roca2} />
      </group>
      <group position={[0,0,0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Arbol- Tronco2']} />
      </group>
      <group position={[0,0,0]} scale={0.57}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Arbol- Tronco2']} />
      </group>
      <group position={[0,0,0]} rotation={[0, 1.36, 0]} scale={0.38}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Arbol- Tronco2']} />
      </group>
      <mesh geometry={nodes.Hojas.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <group position={[0,0,0]} rotation={[0, 0.32, 0]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Arbol- Tronco3']} />
      </group>
      <group position={[0,0,0]} scale={0.14}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Arbol- Tronco3']} />
      </group>
      <group position={[0,0,0]} rotation={[1.47, -0.51, 0.25]} scale={0.11}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Hacha- Madera']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Hacha- metal']} />
      </group>
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Cloud} position={[0,0,0]} rotation={[0, 0.44, 0]} scale={0.71} />
      <mesh geometry={nodes.Icosphere001.geometry} material={nodes.Icosphere001.material} position={[0,0,0]} />
      <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} position={[0,0,0]} />
      <mesh geometry={nodes.Icosphere003.geometry} material={materials.Cloud} position={[0,0,0]} rotation={[0, 0.44, 0]} scale={0.54} />
      <mesh geometry={nodes.Hojas002.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas003.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas004.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas005.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas006.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas007.geometry} material={materials['Arbol - Hoja3']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas008.geometry} material={materials['Arbol - Hoja3']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas009.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas010.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas011.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas012.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas013.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas014.geometry} material={materials['Arbol - Hoja3']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas015.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas016.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas017.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas018.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas019.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas020.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas021.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas022.geometry} material={materials['Arbol - Hoja3']} position={[0,0,0]} scale={0.27} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
