/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree-lv2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.12, 2.32, 1.32]} scale={0.58}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Arbol- Tronco2']} />
      </group>
      <group position={[1.25, 3.96, 2.92]} scale={0.27}>
        <mesh geometry={nodes.Icosphere005.geometry} material={materials['Arbol - Hoja1']} />
        <mesh geometry={nodes.Icosphere005_1.geometry} material={materials['Arbol - Hoja2']} />
        <mesh geometry={nodes.Icosphere005_2.geometry} material={materials['Arbol - Hoja3']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tree-lv2.glb')
