/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree-lv1.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0,0,0]} rotation={[0, 1.09, 0]} scale={0.41}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Arbol- Tronco1']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['Arbol- Tronco2']} />
      </group>
      <mesh geometry={nodes.Hojas023.geometry} position={[0,0,0]} scale={0.27}>
        <meshStandardMaterial {...materials['Arbol - Hoja1']} color={props.c1}/>
      </mesh>
      <mesh geometry={nodes.Hojas024.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas025.geometry} material={materials['Arbol - Hoja2']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas026.geometry} material={materials['Arbol - Hoja1']} position={[0,0,0]} scale={0.27} />
      <mesh geometry={nodes.Hojas027.geometry} material={materials['Arbol - Hoja3']} position={[0,0,0]} scale={0.27} />
    </group>
  )
}

useGLTF.preload('/tree-lv1.glb')
